config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # routes
  #
  resources :blogposts

  # get "/blogpost/new", to: "blogpost#new", as: :new_blogpost

  # get "/blogpost/:id", to: "blogpost#show", as: :blogpost

  # patch "/blogpost/:id", to: "blogpost#update"

  # delete "/blogpost/:id", to: "blogpost#destroy"

  # get "/blogpost/:id/edit", to: "blogpost#edit", as: :edit_blogpost

  # post "/blogpost", to: "blogpost#create", as: :blogposts

  # Defines the root path route ("/")
  root "blogposts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  #scope creates a query function for the controller
  #works on a class level
  #similiar to Blogpost.all
  #it will be Blogpost.draft
  #BlogPost.draft -> "Give me all blog posts that are drafts"
  scope :draft, -> { where(is_draft: true) }
  scope :published, -> { where(is_draft: false) }

  # Scope to fetch draft posts for a specific user
  scope :user_drafts, ->(user) { where(user: user, is_draft: true) }

  # Scope to fetch published posts for a specific user
  scope :user_published, ->(user) { where(user: user, is_draft: false) }

  #works on a object level
  #asks is this object a draft
  #post.draft? -> "Is this specific post a draft?"
  def draft?
    is_draft
  end

  def blog_user?(current_user)
    current_user && user_id == current_user.id
  end

  # Think of the scope as a tool for working with sets of blog posts based on their draft status and
  # the instance method as a way of inspecting the draft status of an individual post.
  #
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :blogposts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_blog_post, except: %i[index new create]
  before_action :authorize_user!, only: %i[edit update destroy]

  def index
    @blogpost = Blogpost.all
  end

  def show
    @blogpost = Blogpost.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def new
    @blogpost = current_user.blogposts.build
  end

  def create
    @blogpost = current_user.blogposts.build(blogpost_params)
    if @blogpost.save
      redirect_to @blogpost, notice: "Blog post created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @blogpost = Blogpost.find(params[:id])
  end

  def update
    @blogpost = Blogpost.find(params[:id])
    if @blogpost.update(blogpost_params)
      redirect_to @blogpost
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blogpost = Blogpost.find(params[:id])
    if @blogpost.destroy
      redirect_to root_path, notice: "Blog post deleted!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def blogpost_params
    params.require(:blogpost).permit(:title, :body, :is_draft, :user_id)
  end

  def set_blog_post
    @blogpost =
      (
        if user_signed_in?
          Blogpost.find(params[:id])
        else
          Blogpost.draft.find(params[:id])
        end
      )
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

  def authorize_user!
    unless current_user == @blogpost.user
      redirect_to root_path,
                  alert: "You are not authorized to perform this action."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogpost_helper.rb
module BlogpostHelper
end

app/views/blogposts/_form.html.erb
<%= form_with model: blogpost do |form| %>

  <% if form.object.errors.any? %>
    <div>
      <% form.object.errors.full_messages.each do | error_message | %>
        <div>
          <%= error_message %>
        </div>
      <% end %>
    </div>
  <% end %>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.label :is_draft%>
    <%= form.check_box :is_draft%>
  </div>

  <%= form.button %>
<% end %>

app/views/blogposts/edit.html.erb
<h1>This is the edit page</h1>

<%= render partial: "form", locals: { blogpost: @blogpost } %>

<%= button_to "Delete", @blogpost, method: :delete, data: {turbo_confirm: "are you sure?"} %>

app/views/blogposts/index.html.erb
<h1>
  Rails Blog
</h1>

<% @blogpost.each do |post| %>
  <div class='border-2 rounded my-3'>
    <h2><%= link_to post.title, blogpost_path(post.id) %></h2>
    <%= post.body %>
    <br>
    <% if post.draft? %>
      <%= "Is this in draft? " + (post.draft? ? "Yes" : "No") %>
    <% end %>
  </div>
<% end %>

app/views/blogposts/new.html.erb
<h1>This is the new page</h1>

<%= render partial: "form", locals: {blogpost: @blogpost} %>

app/views/blogposts/show.html.erb
<h1>this is the show page</h1>

<h2><%= @blogpost.title %></h2>
<%= @blogpost.body %>
<br>
<%# this isnt working %>
<% if @blogpost.blog_user?(current_user)  %>
  <%= link_to "edit blog post", edit_blogpost_path(@blogpost)%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='!no-underline mx-auto prose'>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class='flex justify-between !no-underline'>
      <%= link_to "Home", root_path %>
      <div>
        <% if user_signed_in? %>
          <%= link_to "Profile", edit_user_registration_path %>
          <%= button_to "log out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "log in", new_user_session_path %>
          <%= link_to "sign up", new_user_registration_path %>
        <% end %>
      </div>
    </div>
    <%= yield %>
    <div class="border-1 p-4">
      <%= link_to "create new blog post", new_blogpost_path if user_signed_in? %>
    </div>
  </body>
</html>